version: "3"

services:
  app:
    build: .
    depends_on:
      - elasticsearch
    volumes:
      - .:/app
    entrypoint:
      [
        "./wait-for-it.sh",
        "-t",
        "30",
        "elasticsearch:9200",
        "--",
        "python3",
        "code/news_collector.py"
      ]
    networks:
      - netlab_network

  elasticsearch:
    image: elasticsearch:8.3.2
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    networks:
      - netlab_network
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data

  kibana:
    image: kibana:8.3.2
    ports:
      - "5601:5601"
    networks:
      - netlab_network
    environment:
      - ELASTICSEARCH_HOSTS=["http://elasticsearch:9200"]

networks:
  netlab_network:


volumes:
  elasticsearch_data:


